
var HeadID_SEX = {
    '0' : ENUM_SEX.MALE,
    '1' : ENUM_SEX.MALE,
    '2' : ENUM_SEX.MALE,
    '3' : ENUM_SEX.MALE,
    '4' : ENUM_SEX.MALE,
    '5' : ENUM_SEX.MALE,
    '6' : ENUM_SEX.MALE,
    '7' : ENUM_SEX.MALE,
    '8' : ENUM_SEX.MALE,
    '9' : ENUM_SEX.MALE,
    '10' : ENUM_SEX.MALE,
    '11' : ENUM_SEX.MALE,
    '12' : ENUM_SEX.MALE,
    '13' : ENUM_SEX.MALE,
    '14' : ENUM_SEX.FEMALE,
    '15' : ENUM_SEX.FEMALE,
    '16' : ENUM_SEX.FEMALE,
    '17' : ENUM_SEX.FEMALE,
    '18' : ENUM_SEX.FEMALE,
    '19' : ENUM_SEX.FEMALE,
}